In [103]:
from utils.data_separation import prepare_input_data
from utils.data_model_preprocessing import preprocessing, add_wind_speed, wind_radians_degrees, direction_sector
from utils.errors import errors

import pandas as pd
import numpy as np

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [104]:
obs_df, pred_df = prepare_input_data('output.txt')

n_df, e_df, s_df, w_df = preprocessing(obs_df)

errors_df, models = errors([n_df, e_df, s_df, w_df])

In [105]:
errors_df.head()

  DataFrame  Coefficient  Y-Intercept  MAE as %  MSE as %
0     North        61.56        37.62     67.06     55.20
1      East       122.27       -13.04     66.10     64.99
2     South       130.19      -128.42     42.75     27.97
3      West        91.27        -4.58     97.98    223.12

# From Here practice

In [106]:
pred_df.head(3)

            date_time  U  V
0 2009-10-20 14:00:00 -9 -9
1 2009-10-20 14:00:00 -9 -9
2 2009-10-20 14:00:00 -9 -9

In [107]:
def prepare_data_for_predition(df):
    df['Speed (m/ps)'] = df.apply(add_wind_speed, axis=1)
    df['Direction (degrees)'] = df.apply(wind_radians_degrees, axis=1)
    df['Direction (sector)'] = df.apply(direction_sector, axis=1)
    return df

In [108]:
prepped_df = prepare_data_for_predition(pred_df)
prepped_df

,date_time,U,V,Speed (m/ps),Direction (degrees),Direction (sector)
0,2009-10-20 14:00:00,-9,-9,1.006231,225.000000,West
1,2009-10-20 14:00:00,-9,-9,1.006231,225.000000,West
2,2009-10-20 14:00:00,-9,-9,1.006231,225.000000,West
3,2009-10-20 14:00:00,-9,-9,1.006231,225.000000,West
4,2009-10-20 14:00:00,-9,-9,1.006231,225.000000,West
5,2009-10-20 14:00:00,-9,-9,1.006231,225.000000,West
6,2009-10-20 14:00:00,-9,-9,1.006231,225.000000,West
7,2009-10-20 14:00:00,-9,-9,1.006231,225.000000,West
8,2009-10-20 14:00:00,-9,-9,1.006231,225.000000,West
9,2009-10-25 23:00:00,-10,3,0.583095,286.699244,West
10,2009-10-25 23:00:00,-10,3,0.583095,286.699244,West
11,2009-10-25 23:00:00,-10,3,0.583095,286.699244,West
12,2009-10-25 23:00:00,-10,3,0.583095,286.699244,West
13,2009-10-25 23:00:00,-10,3,0.583095,286.699244,West
14,2009-10-25 23:00:00,-10,3,0.583095,286.699244,West
15,2009-10-25 23:00:00,-10,3,0.583095,286.699244,West
16,2009-10-25 23:00:00,-10,3,0.583095,286.699244,West
17,2009-10-25 23:00:00,-10,3,0.583095,286.699244,West

In [109]:
model_mapping = {
    'North': 0,
    'East': 1,
    'South': 2,
    'West': 3
}

In [115]:
def make_prediction(row, models):
    model_mapping = {
        'North': 0,
        'East': 1,
        'South': 2,
        'West': 3
    }
    direction = row['Direction (sector)']
    model_index = model_mapping.get(direction)
    model = models[model_index]

    # Reshape the input data X
    X = row['Speed (m/ps)'].reshape(-1, 1)

    y_pred = model.predict(X)
    return y_pred

In [116]:
prepped_df['pred'] = prepped_df.apply(make_prediction, axis=1, models=models)
prepped_df.head()

AttributeError: 'float' object has no attribute 'values'